#set active environment
spring: 
    profiles: 
        active: dev
    devtools: 
        restart: 
            enabled: false
    servlet:
        multipart:
            maxFileSize: 104857600
            maxRequestSize: 104857600
server: 
    port: 8080
    tomcat:
        max-threads: 1000
        max-connections: 10000
#############SWAGGER CONFIG#################
siren:
    swagger:
        title: SirenⅠ
        description: 海妖之躯 The kernel of Siren
        termsOfServiceUrl: www.siren.com
        version: 1.0.0